---
branch: master
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - terraform
  - secrets
skip-check:
  - CKV_AWS_356  # wildcard resource in pinned external codebuild module policy doc
